server:
  port: 9093

spring:
  profiles:
    active: dev
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${AWS_MYSQL_URL}
    username: ${AWS_MYSQL_USERNAME}
    password: ${AWS_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect